### ISSUE TITLE
Enhancement: Please resize heading band to allow centering above artificial horizon

### ISSUE THREAD

**Issue by aheyer** [night-ghost/minimosd-extra#136]
The artificial horizon has a proper width to be placed centred on screen. The heading band is one character to small/width, so you can't place it centred and aligned to the attitude indicator.

**Comment by thecodingfrog** [comment]
It has to be like this because of centering needs. If you increase it to 12 chars how will you center North ?

**Comment by thecodingfrog** [comment]
Ok I've done it, it's not so bad. I changed few things by the way and updated charset to make baseline more confortable

**Comment by aheyer** [comment]
After posting my enhancement suggestion I thought the same: How to center a direction character with an even size? But it's possible like mwosd project shows. Seems you have to split characters into two positions.

Unfortunately your recent change did not correct the issue. You still can't line up the center of the artificial horizon to the center of the heading rose. Look at the GUI screen-shot:

![osd config](https://cloud.githubusercontent.com/assets/7488479/15547213/21e21ef8-22a3-11e6-97f9-8d0fbc80e20d.jpg)

The new arrow can't be centred. Personally I even don't feel a need for this arrow because I'd like to put the heading degree number above the rose and have the decimal ten position at center.

There's also another bug show in the screen shot: Look at the right upper edge. Under the time I have the trip's travel distance. Both fields have the same width in the GUI but if I place them aligned, the unit mark shifts one position to the right. So I have to displace the travel field to get right alignment.

**Comment by thecodingfrog** [comment]
Maybe I can fork this project to share my mods, but I'am a newbie git user

Le 25 mai 2016 18:32, Andreas Heyer <notifications@github.com> a écrit :

After posting my enhancement suggestion I thought the same: How to center a direction character with an even size? But it's possible like mwosd project shows. Seems you have to split characters into two positions.

Unfortunately your recent change did not correct the issue. You still can't line up the center of the artificial horizon to the center of the heading rose. Look at the GUI screen-shot:

 

The new arrow can't be centred. Personally I even don't feel a need for this arrow because I'd like to put the heading degree number above the rose and have the decimal ten position at center.

There's also another bug show in the screen shot: Look at the right upper edge. Under the time I have the trip's travel distance. Both fields have the same width in the GUI but if I place them aligned, the unit mark shifts one position to the right. So I have to displace the travel field to get right alignment.

**Comment by thecodingfrog** [comment]
I forked the project if you want to try it out

**Comment by thecodingfrog** [comment]
![img_20160525_213848](https://cloud.githubusercontent.com/assets/12624593/15626691/da5147b4-24cb-11e6-94ec-e4ae4f626627.jpg)

**Comment by aheyer** [comment]
Looks good. Only problem now: You need 3 lines instead of 2. Personally I don't need the marker, it just suffice that the band is centred now. If I use the marker it has be be mirrored to be put under the rose band. Because I place the heading on top of the screen.mirrored to your style. So we need an additional mirrored center mark. :)

Thank you for your efforts. The best way to spread your work is to send a pull request to night-ghost. I'm in doubt that many users will change to your fork.

Do you have any clue what the new symbol in front of the heading is? This double arrow in my screen or the unidentifiable symbol in yours?

**Comment by thecodingfrog** [comment]
the center mark can be removed, just click the option for heading rose. I'm afraid we can't do a bottom center mark, as we have to use chars from charset file that is limited.
In front of the 18° I have the arrow, it appears blured on this photo

**Comment by night-ghost** [comment]
Guys, the screen has an even number of columns, and you'll never  center odd-chars panel.

Low marker I'll made

**Comment by night-ghost** [comment]
see v846
